name: Publish main
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mendax1234' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.ff only

          git fetch origin main
          (git checkout main && git pull) || git checkout -b main origin/main

          git fetch origin main
          (git checkout main && git pull) || git checkout -b main origin/main

          if git merge-base --is-ancestor main main; then
            echo "No merge is necessary"
            exit 0
          fi;

          git merge --ff-only main

      - name: Push
        if: env.PUBLISH_main == 'true' || github.event.action == 'workflow_dispatch'
        env:
          PUBLISH_main: ${{ secrets.PUBLISH_main }}
        run: |
          git push origin main
